### ISSUE TITLE
Deprecate the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/k-NN#307]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x until further notice to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.

**Describe the solution you'd like**
Replace the terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- Replace "master" in code comment internal class name.

When being compatible with OpenSearch 3.0:
- Replace "master" in the reference to OpenSearch Java API
  - [x] clusterService.state().nodes().isLocalNodeElectedMaster() -> isLocalNodeElectedClusterManager() (new API is available in v2.2)
  - [x] import org.opensearch.action.support.master.TransportMasterNodeAction -> import org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction (new API is available in v2.2)
  - ~~[ ]~~ import org.opensearch.action.support.master.AcknowledgedResponse -> import org.opensearch.action.support.clustermanager.AcknowledgedResponse (will be available in version 3.0 and track in separate issue)

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by dblock** [comment]
For 2.0, at a minimum please ensure that the plugin is not calling any deprecated APIs in core or another plugin, and confirm below, then remove the 2.0.0 label. If you have time, do the complete deprecation as described in this issue.

**Comment by martin-gaievski** [comment]
@dblock do we expect any more "deprecation" changes on core api for 2.0? For instance knn refers[ this package](https://github.com/opensearch-project/OpenSearch/tree/main/server/src/main/java/org/opensearch/action/support/master) in import section, seems it's not deprecated yet.

**Comment by dblock** [comment]
Yes, thanks for point this out. I'll reopen this issue, now that we know that k-nn is referring to something with `master` in core and label it for 2.1. /cc: @tlfeng

**Comment by naveentatikonda** [comment]
@tlfeng Besides these [packages](https://github.com/opensearch-project/OpenSearch/tree/main/server/src/main/java/org/opensearch/action/support/master), knn also depends on these 2 methods [masterOperation](https://github.com/opensearch-project/OpenSearch/blob/996d33adb22ac6a523962166f3677f8dc6ac9c1f/server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeAction.java#L123) and [clusterService.state().nodes().isLocalNodeElectedMaster()](https://github.com/opensearch-project/OpenSearch/blob/cc0e66b1dcc2cfe17b76bcea1168ebb996fbb090/server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java#L115). Does any of these methods will be deprecated for 2.0 in opensearch-core?

**Comment by dblock** [comment]
@tlfeng Please confirm whether you expect any more deprecations in core after today? Is that a bug or a feature? :)

**Comment by tlfeng** [comment]
Hi @naveentatikonda The package and method names you pointed out will be replaced in OpenSearch 3.0. I haven't started yet, and will the update.
I called those public method and package from OpenSearch as "OpenSearch Java API", the replacement is tracked in issue https://github.com/opensearch-project/OpenSearch/issues/1684. It will be ready before OpenSearch 3.0 and I will complete in advance.
If the issue is used for pending items for 2.0 release, then the issue is resolved.

**Comment by anasalkouz** [comment]
Java APIs completed and released on 2.2.
@naveentatikonda  Could you please complete the remaining part from your end? let's target 2.3 for all usages.

**Comment by naveentatikonda** [comment]
@anasalkouz Thanks for the update. Will incorporate those changes for 2.3

**Comment by naveentatikonda** [comment]
> @naveentatikonda anything remaining? can you close the issue?

@anasalkouz Still these two packages needs to be updated. They are still not supported by opensearch core and is expected to be ready by 3.0 :

org.opensearch.action.support.master.AcknowledgedRequest -> org.opensearch.action.support.clusterManager.AcknowledgedRequest

org.opensearch.action.support.master.AcknowledgedResponse -> org.opensearch.action.support.clusterManager.AcknowledgedResponse

Also, does the whitelist changes needs to be shipped with 2.3 release or pushed to 3.0 release ?

**Comment by tlfeng** [comment]
@naveentatikonda k-NN repository have done with all changes required for 2.x release, and the remaining effort will be tracked in separate issue as part of 3.0. Thank you!

The remaining effort means the following Java APIs
```
org.opensearch.action.support.master.AcknowledgedRequest
  -> org.opensearch.action.support.clusterManager.AcknowledgedRequest

org.opensearch.action.support.master.AcknowledgedResponse
  -> org.opensearch.action.support.clusterManager.AcknowledgedResponse

Map<ScriptContext<?>, List<Whitelist>> getContextWhitelists()
 -> Map<ScriptContext<?>, List<Allowlist>> getContextAllowlists()
 
org.opensearch.painless.spi.Whitelist -> Allowlist
org.opensearch.painless.spi.WhitelistLoader -> AllowlistLoader
```
